# Generated by Django 4.1.5 on 2023-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_phone_number', models.CharField(max_length=15)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('discarded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('date_won', models.DateTimeField(auto_now_add=True)),
                ('amount_won', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
